### ISSUE TITLE
在解析如下 SVG 时报 replace 错误

### ISSUE THREAD

**Issue by creamidea** [yanbingbing/svg2react-loader#2]
### 错误

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'replace' of undefined
    at /usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:31:31
    at Array.forEach (<anonymous>)
    at sanitizeStyleNodes (/usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:28:11)
    at /usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:97:17
    at Array.forEach (<anonymous>)
    at sanitize (/usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:90:64)
    at /usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:55:13
    at Array.forEach (<anonymous>)
    at sanitize (/usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:54:17)
    at /usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/util/sanitize.js:100:17
Emitted 'error' event at:
    at Parser.exports.Parser.Parser.parseString (/usr/local/lib/node_modules/@ali/vdev/node_modules/_xml2js@0.4.19@xml2js/lib/parser.js:326:16)
    at Parser.parseString (/usr/local/lib/node_modules/@ali/vdev/node_modules/_xml2js@0.4.19@xml2js/lib/parser.js:5:59)
    at render (/usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/index.js:69:19)
    at /usr/local/lib/node_modules/@ali/vdev/node_modules/_svg2react-loader@1.0.3@svg2react-loader/index.js:18:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

### 期望

不报错，正常转换

### 出错的 SVG 内容
```svg
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200" class="icon" p-id="3710" style="" t="1535285544041" version="1.1" viewBox="0 0 1024 1024">
    <defs>
        <style type="text/css"/>
    </defs>
    <path fill="#4C4C4C" d="M414.08 634.88a31.36 31.36 0 0 1-23.04-8.96 197.76 197.76 0 0 1 9.6-288.64l166.4-166.4a213.76 213.76 0 0 1 302.08-5.76A204.16 204.16 0 0 1 931.2 320a220.8 220.8 0 0 1-64 152.32l-79.36 70.4a32 32 0 1 1-43.52-47.36l76.8-71.04a152.32 152.32 0 0 0 44.8-104.32 142.08 142.08 0 0 0-40.96-104.32 148.48 148.48 0 0 0-209.92 3.84L448 384a133.12 133.12 0 0 0-9.6 192 32.64 32.64 0 0 1 0 46.08 33.92 33.92 0 0 1-24.32 12.8z m-108.8 309.12a204.8 204.8 0 0 1-149.76-59.52 204.16 204.16 0 0 1-59.52-149.76 220.8 220.8 0 0 1 64-152.32l76.8-72.32a32 32 0 1 1 43.52 46.72L202.24 625.92a152.32 152.32 0 0 0-44.16 104.96A142.08 142.08 0 0 0 199.04 832a148.48 148.48 0 0 0 213.12 0L576 667.52a144.64 144.64 0 0 0 9.6-206.08 80 80 0 0 0-29.44-17.28 31.36 31.36 0 0 1-21.76-39.68 33.92 33.92 0 0 1 41.6-26.24 141.44 141.44 0 0 1 57.6 33.28 209.28 209.28 0 0 1-11.52 298.24l-166.4 166.4a221.44 221.44 0 0 1-150.4 68.48z" p-id="3711"/>
</svg>
```

**Comment by gbk** [comment]
请将 svg 中 style 空属性和 style 空结点删掉，就可以解决你的问题。
欢迎 PR！

**Comment by creamidea** [comment]
@gbk 嗯嗯，是的。我们就是这么临时解决了  :)

后面有空来这里提 PR
